name: taskmaster
description: TaskMaster - Gerenciador de Tarefas Inteligente

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_slidable: ^3.0.1
  shared_preferences: ^2.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
